var e* = CatchableError.newException("failure")
# raise an unhandled exception
raise e